#!/usr/bin/env bats
# tests/cast-settings-hook-wiring.bats
# Asserts that settings.json correctly wires all required hook entries.
#
# These tests use semantic checks (find by id) rather than strict positional
# assumptions. After the install.sh fragment-merge refactor (Phase 2,
# 2026-05-05), settings.json is regenerated by concatenating
# managed-settings.d/*.json fragments. Order and total count are stable but
# not all entries carry top-level `id` fields, and additional Stop entries
# may be present from non-journal fragments — the tests must tolerate that.

load 'test_helper/bats-support/load'
load 'test_helper/bats-assert/load'

SETTINGS="${BATS_TEST_DIRNAME}/../settings.json"

@test "settings.json has at least 3 SessionStart entries" {
  run python3 -c "
import json
with open('$SETTINGS') as f:
  s = json.load(f)
starts = s['hooks'].get('SessionStart', [])
assert len(starts) >= 3, f'Expected at least 3 SessionStart entries, got {len(starts)}'
print('OK')
"
  assert_output "OK"
}

@test "SessionStart contains cast-time-context and cast-session-start-journal entries" {
  run python3 -c "
import json
with open('$SETTINGS') as f:
  s = json.load(f)
starts = s['hooks'].get('SessionStart', [])
ids = [h.get('id', '') for h in starts]
assert 'cast-time-context' in ids, f'cast-time-context missing from SessionStart ids: {ids}'
assert 'cast-session-start-journal' in ids, f'cast-session-start-journal missing from SessionStart ids: {ids}'
print('OK')
"
  assert_output "OK"
}

@test "Stop contains an entry with id cast-journal-session-end" {
  run python3 -c "
import json
with open('$SETTINGS') as f:
  s = json.load(f)
stops = s['hooks'].get('Stop', [])
ids = [h.get('id', '') for h in stops]
assert 'cast-journal-session-end' in ids, f'cast-journal-session-end missing from Stop ids: {ids}'
print('OK')
"
  assert_output "OK"
}

@test "cast-session-start-journal hook points to an existing script" {
  run python3 -c "
import json, os
with open('$SETTINGS') as f:
  s = json.load(f)
starts = s['hooks'].get('SessionStart', [])
journal_entry = next((h for h in starts if h.get('id') == 'cast-session-start-journal'), None)
assert journal_entry is not None, 'cast-session-start-journal entry missing'
cmd = journal_entry['hooks'][0]['command']
script_path = os.path.expanduser(cmd.replace('bash ', '', 1).strip())
assert os.path.isfile(script_path), f'Script not found: {script_path}'
print('OK')
"
  assert_output "OK"
}

@test "cast-journal-session-end hook points to an existing script" {
  run python3 -c "
import json, os
with open('$SETTINGS') as f:
  s = json.load(f)
stops = s['hooks'].get('Stop', [])
journal_stop = next((h for h in stops if h.get('id') == 'cast-journal-session-end'), None)
assert journal_stop is not None, 'cast-journal-session-end entry missing from Stop'
cmd = journal_stop['hooks'][0]['command']
script_path = os.path.expanduser(cmd.replace('bash ', '', 1).strip())
assert os.path.isfile(script_path), f'Script not found: {script_path}'
print('OK')
"
  assert_output "OK"
}

@test "cast-journal-session-end has timeout 5" {
  run python3 -c "
import json
with open('$SETTINGS') as f:
  s = json.load(f)
stops = s['hooks'].get('Stop', [])
journal_stop = next((h for h in stops if h.get('id') == 'cast-journal-session-end'), None)
assert journal_stop is not None, 'cast-journal-session-end entry missing'
timeout = journal_stop['hooks'][0].get('timeout')
assert timeout == 5, f'Expected timeout 5, got {timeout}'
print('OK')
"
  assert_output "OK"
}
