#!/usr/bin/env bash
# cast-branch-groomer-schedule.sh — Weekly dry-run branch grooming report
#
# Runs the branch groomer in --dry-run mode and writes a dated markdown
# report to ~/.claude/reports/branch-grooming-<date>.md.
#
# Recommended cron line (Sunday 06:00 local time):
#   0 6 * * 0 bash /path/to/scripts/cast-branch-groomer-schedule.sh
# or via cast reminders:
#   /schedule weekly "bash scripts/cast-branch-groomer-schedule.sh"
#
# Output: ~/.claude/reports/branch-grooming-YYYY-MM-DD.md
# Exit:   0 always (report is advisory)
#
# Usage: bash scripts/cast-branch-groomer-schedule.sh [--repo <path>]

set -euo pipefail

# ── Subprocess guard ──────────────────────────────────────────────────────
if [[ "${CLAUDE_SUBPROCESS:-0}" == "1" ]]; then exit 0; fi

# ── Error logging ─────────────────────────────────────────────────────────
mkdir -p "${HOME}/.claude/logs" 2>/dev/null || true
_log_error() {
  printf '[%s] ERROR %s: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$0" "$1" \
    >> "${HOME}/.claude/logs/hook-errors.log" 2>/dev/null || true
}

# ── Parse flags ───────────────────────────────────────────────────────────
REPO_DIR=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_DIR="$2"; shift 2 ;;
    --help|-h)
      grep '^#' "$0" | grep -v '^#!' | sed 's/^# \?//'
      exit 0
      ;;
    *)
      printf '[cast-branch-groomer-schedule] Unknown flag: %s\n' "$1" >&2
      shift
      ;;
  esac
done

# ── Locate groomer script ─────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GROOMER="${SCRIPT_DIR}/cast-branch-groomer.sh"

# Fallback to installed copy
if [[ ! -f "$GROOMER" ]]; then
  GROOMER="${HOME}/.claude/scripts/cast-branch-groomer.sh"
fi

if [[ ! -f "$GROOMER" ]]; then
  _log_error "cast-branch-groomer.sh not found at $GROOMER"
  printf '[cast-branch-groomer-schedule] ERROR: groomer not found\n' >&2
  exit 0  # advisory — never block
fi

# ── Prepare output paths ──────────────────────────────────────────────────
REPORTS_DIR="${HOME}/.claude/reports"
mkdir -p "$REPORTS_DIR" 2>/dev/null || true

DATE_STAMP="$(date +%Y-%m-%d)"
REPORT_FILE="${REPORTS_DIR}/branch-grooming-${DATE_STAMP}.md"

# ── Build groomer flags ───────────────────────────────────────────────────
# Default: dry-run (report only, no deletions).
# Set CAST_GROOM_AUTO_APPLY=1 to enable live deletions.
# The audit report is always written regardless of mode.
if [[ "${CAST_GROOM_AUTO_APPLY:-0}" == "1" ]]; then
  GROOMER_FLAGS=("--apply" "--worktrees")
else
  GROOMER_FLAGS=("--dry-run" "--worktrees")
fi
if [[ -n "$REPO_DIR" ]]; then
  GROOMER_FLAGS+=("--repo" "$REPO_DIR")
fi

# ── Run groomer, capture output ───────────────────────────────────────────
GROOMER_OUTPUT=""
if ! GROOMER_OUTPUT="$(bash "$GROOMER" "${GROOMER_FLAGS[@]}" 2>&1)"; then
  _log_error "groomer exited non-zero (advisory)"
fi

# ── Parse output into sections ────────────────────────────────────────────
SWARM_LINES=""
WORKTREE_AGENT_LINES=""
MERGED_LINES=""
WORKTREE_DIR_LINES=""
SUMMARY_LINE=""
KEPT_LINES=""

while IFS= read -r line; do
  case "$line" in
    *"Would delete branch: cast-swarm-"*)
      SWARM_LINES="${SWARM_LINES}- ${line#*Would delete branch: }"$'\n'
      ;;
    *"Would delete branch: worktree-agent-"*)
      WORKTREE_AGENT_LINES="${WORKTREE_AGENT_LINES}- ${line#*Would delete branch: }"$'\n'
      ;;
    *"Would delete branch: "*)
      MERGED_LINES="${MERGED_LINES}- ${line#*Would delete branch: }"$'\n'
      ;;
    *"Would remove worktree: "*)
      WORKTREE_DIR_LINES="${WORKTREE_DIR_LINES}- ${line#*Would remove worktree: }"$'\n'
      ;;
    *"Keeping "*)
      KEPT_LINES="${KEPT_LINES}- ${line#*\] }"$'\n'
      ;;
    "Groomed"*)
      SUMMARY_LINE="$line"
      ;;
  esac
done <<< "$GROOMER_OUTPUT"

# ── Write report ──────────────────────────────────────────────────────────
{
  printf '# Branch Grooming Report — %s\n\n' "$DATE_STAMP"
  printf 'Generated by `scripts/cast-branch-groomer-schedule.sh` (dry-run)\n\n'
  printf '> Review this report before running `cast clean --apply` to delete listed branches.\n\n'

  printf '## Summary\n\n'
  if [[ -n "$SUMMARY_LINE" ]]; then
    printf '%s\n\n' "$SUMMARY_LINE"
  else
    printf '_No summary line produced by groomer._\n\n'
  fi

  printf '## Stale Swarm Branches (cast-swarm-* > 14 days, no open PR)\n\n'
  if [[ -n "$SWARM_LINES" ]]; then
    printf '%s\n' "$SWARM_LINES"
  else
    printf '_None found._\n\n'
  fi

  printf '## Stale Worktree-Agent Branches (worktree-agent-* > 7 days)\n\n'
  if [[ -n "$WORKTREE_AGENT_LINES" ]]; then
    printf '%s\n' "$WORKTREE_AGENT_LINES"
  else
    printf '_None found._\n\n'
  fi

  printf '## Merged Feature/Fix Branches ([gone] upstream)\n\n'
  if [[ -n "$MERGED_LINES" ]]; then
    printf '%s\n' "$MERGED_LINES"
  else
    printf '_None found._\n\n'
  fi

  printf '## Dead Worktree Directories\n\n'
  if [[ -n "$WORKTREE_DIR_LINES" ]]; then
    printf '%s\n' "$WORKTREE_DIR_LINES"
  else
    printf '_None found._\n\n'
  fi

  if [[ -n "$KEPT_LINES" ]]; then
    printf '## Kept (whitelisted or has open PR)\n\n'
    printf '%s\n' "$KEPT_LINES"
  fi

  printf '## Actions\n\n'
  printf '```bash\n'
  printf '# Delete stale branches only:\n'
  printf 'cast clean --apply\n\n'
  printf '# Delete stale branches AND dead worktree directories:\n'
  printf 'cast clean --apply --worktrees\n'
  printf '```\n'
} > "$REPORT_FILE" 2>/dev/null || {
  _log_error "failed to write report to $REPORT_FILE"
  exit 0
}

printf '[cast-branch-groomer-schedule] Report written: %s\n' "$REPORT_FILE"
exit 0
