#!/usr/bin/env bash
# cast-branch-groomer-schedule.sh — scheduled multi-repo branch grooming.
#
# Runs the branch groomer across the LIVE CAST repos and writes a dated markdown
# report to ~/.claude/reports/branch-grooming-<date>.md.
#
# Repo selection (precedence): --repo <path>  >  $CAST_GROOM_REPOS  >  built-in
# live-repo list. Only LIVE repos are groomed by default; dormant/ecosystem repos
# (forge, aether, project-engram, stratum) are intentionally EXCLUDED — their
# unmerged worktree-agent-* branches would be force-deleted by the groomer's
# -d||-D fallback. Groom those manually with an explicit --repo when intended.
#
# Mode: dry-run by default (report only). Set CAST_GROOM_AUTO_APPLY=1 to enable
# live deletions (the scheduled launchd job sets this; the script default is safe).
#
# Recommended schedule (Sunday 06:00 local): com.cast.branch-groomer.plist
# Output: ~/.claude/reports/branch-grooming-YYYY-MM-DD.md
# Exit:   0 always (advisory)
#
# Usage: bash scripts/cast-branch-groomer-schedule.sh [--repo <path>]

set -euo pipefail

# ── Subprocess guard ──────────────────────────────────────────────────────
if [[ "${CLAUDE_SUBPROCESS:-0}" == "1" ]]; then exit 0; fi

# ── Error logging ─────────────────────────────────────────────────────────
mkdir -p "${HOME}/.claude/logs" 2>/dev/null || true
_log_error() {
  printf '[%s] ERROR %s: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$0" "$1" \
    >> "${HOME}/.claude/logs/hook-errors.log" 2>/dev/null || true
}

# ── Parse flags ───────────────────────────────────────────────────────────
REPO_DIR=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --repo) REPO_DIR="$2"; shift 2 ;;
    --help|-h)
      grep '^#' "$0" | grep -v '^#!' | sed 's/^# \?//'
      exit 0
      ;;
    *)
      printf '[cast-branch-groomer-schedule] Unknown flag: %s\n' "$1" >&2
      shift
      ;;
  esac
done

# ── Locate groomer script ─────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GROOMER="${SCRIPT_DIR}/cast-branch-groomer.sh"
if [[ ! -f "$GROOMER" ]]; then
  GROOMER="${HOME}/.claude/scripts/cast-branch-groomer.sh"
fi
if [[ ! -f "$GROOMER" ]]; then
  _log_error "cast-branch-groomer.sh not found at $GROOMER"
  printf '[cast-branch-groomer-schedule] ERROR: groomer not found\n' >&2
  exit 0  # advisory — never block
fi

# ── Prepare output paths ──────────────────────────────────────────────────
REPORTS_DIR="${HOME}/.claude/reports"
mkdir -p "$REPORTS_DIR" 2>/dev/null || true
DATE_STAMP="$(date +%Y-%m-%d)"
REPORT_FILE="${REPORTS_DIR}/branch-grooming-${DATE_STAMP}.md"

# ── Build groomer mode flags (--repo is added per-repo below) ─────────────
# Default: dry-run (report only). CAST_GROOM_AUTO_APPLY=1 enables live deletions.
if [[ "${CAST_GROOM_AUTO_APPLY:-0}" == "1" ]]; then
  MODE_FLAGS=("--apply" "--worktrees")
  MODE_LABEL="apply"
else
  MODE_FLAGS=("--dry-run" "--worktrees")
  MODE_LABEL="dry-run"
fi

# ── Resolve the repo list ─────────────────────────────────────────────────
REPOS=()
if [[ -n "$REPO_DIR" ]]; then
  REPOS=("$REPO_DIR")
elif [[ -n "${CAST_GROOM_REPOS:-}" ]]; then
  IFS=': ' read -r -a REPOS <<< "$CAST_GROOM_REPOS"   # space- or colon-separated
else
  REPOS=(
    "${HOME}/Projects/personal/claude-agent-team"
    "${HOME}/Projects/personal/cast-website"
    "${HOME}/Projects/personal/cast-hooks"
    "${HOME}/Projects/personal/cast-claudes_journal"
  )
fi

# ── Run groomer per repo, accumulate a combined report ────────────────────
{
  printf '# Branch Grooming Report — %s\n\n' "$DATE_STAMP"
  printf 'Generated by `cast-branch-groomer-schedule.sh` (mode: **%s**)\n\n' "$MODE_LABEL"
  if [[ "$MODE_LABEL" == "dry-run" ]]; then
    printf '> Dry-run — review, then `cast clean --apply` or set `CAST_GROOM_AUTO_APPLY=1`.\n\n'
  fi
} > "$REPORT_FILE" 2>/dev/null || { _log_error "failed to write report to $REPORT_FILE"; exit 0; }

groomed=0
for repo in "${REPOS[@]}"; do
  [[ -z "$repo" ]] && continue
  if [[ ! -d "$repo/.git" ]]; then
    { printf '## %s\n\n_skipped — not a git repo_\n\n' "$(basename "$repo")"; } >> "$REPORT_FILE" 2>/dev/null || true
    continue
  fi
  GROOMER_OUTPUT=""
  if ! GROOMER_OUTPUT="$(bash "$GROOMER" "${MODE_FLAGS[@]}" --repo "$repo" 2>&1)"; then
    _log_error "groomer non-zero for $repo (advisory)"
  fi
  {
    printf '## %s\n\n```\n%s\n```\n\n' "$(basename "$repo")" "$GROOMER_OUTPUT"
  } >> "$REPORT_FILE" 2>/dev/null || true
  groomed=$((groomed + 1))
done

printf '[cast-branch-groomer-schedule] Report written: %s (%d repo(s), mode=%s)\n' \
  "$REPORT_FILE" "$groomed" "$MODE_LABEL"
exit 0
