#!/usr/bin/env bash
# cast-check-derived-counts.sh — recompute EVERY derived count in the repo and
# name the stale ones with the command that regenerates them.
#
# Why this exists (J-5): a release moves more derived counts at once than any
# other change, and the counts live in six places maintained by four different
# mechanisms. Two of them had drifted silently more than once — the skip ledger's
# file count went 25 -> 29 unnoticed because its drift test enforced only the
# call-site number, and a stats regen was missed on a PR and cost a CI round trip.
#
# The rule this file obeys: RECOMPUTE, never proxy. A "has this file changed
# recently?" heuristic is exactly true and says nothing about whether the number
# in it is right. Every check below derives the real value and compares it.
#
# Exit 0 = every derived count matches. Exit 1 = at least one is stale.
# Never modifies anything — reporting only.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

_fail=0
_checks=0

_ok()   { printf '  [ok]    %-34s %s\n' "$1" "$2"; }
_stale() {
  printf '  [STALE] %-34s %s\n' "$1" "$2"
  printf '          regenerate: %s\n' "$3"
  _fail=1
}

printf 'Derived-count sweep (recomputed, not inferred)\n'
printf -- '----------------------------------------------------------\n'

# 1 + 2. cast-stats.json and the README badges/sentinels. Both generators carry
# their own --check mode, which derives from the tree and diffs; reuse them
# rather than reimplementing, so this file cannot drift from the generators.
_checks=$((_checks + 1))
if bash scripts/gen-cast-stats.sh --check >/dev/null 2>&1; then
  _ok "cast-stats.json" "in sync"
else
  _stale "cast-stats.json" "differs from the tree" "bash scripts/gen-cast-stats.sh"
fi

_checks=$((_checks + 1))
if bash scripts/gen-stats.sh --check >/dev/null 2>&1; then
  _ok "README badges + sentinels" "in sync"
else
  _stale "README badges + sentinels" "differs from the tree" "bash scripts/gen-stats.sh"
fi

# 3. Skip ledger — BOTH halves. The file-count half went unenforced for two
# drift cycles while the call-site half was green, which is why the check is the
# script and not an inline recount.
_checks=$((_checks + 1))
_skip_out="$(bash scripts/cast-check-skip-ledger.sh 2>&1)"
if [ $? -eq 0 ]; then
  _ok "docs/test-skip-ledger.md" "${_skip_out#OK: skip ledger in sync — }"
else
  _stale "docs/test-skip-ledger.md" "$_skip_out" "bash scripts/cast-check-skip-ledger.sh (prints the real numbers)"
fi

# 4. Agent roster count in CLAUDE.md. NOT generated by anything — the README
# badge is, but this prose copy is hand-maintained and nothing checked it.
_checks=$((_checks + 1))
_agents_real="$(find agents/core -maxdepth 1 -name '*.md' | wc -l | tr -d ' ')"
_agents_doc="$(grep -oE 'holds the [0-9]+ canonical' CLAUDE.md 2>/dev/null | grep -oE '[0-9]+' | head -1)"
if [ "${_agents_doc:-}" = "$_agents_real" ]; then
  _ok "CLAUDE.md agent roster count" "$_agents_real"
else
  _stale "CLAUDE.md agent roster count" "claims ${_agents_doc:-<none>}, tree has $_agents_real" \
         "edit CLAUDE.md: 'holds the $_agents_real canonical agent definitions'"
fi

# 5. The completions dispatch-table literal appears TWICE in the same test — in
# the asserted comparison AND in the test NAME. The body fails loudly on drift;
# the name just quietly becomes wrong, and a wrong test name is read as fact.
_checks=$((_checks + 1))
_cd_file="tests/cast-completions-drift.bats"
_name_n="$(grep -oE '@test "zsh: generated subcommands region == dispatch table \(count [0-9]+\)"' "$_cd_file" 2>/dev/null | grep -oE '[0-9]+' | head -1)"
_body_n="$(grep -oE '\[ "\$count" -eq [0-9]+ \]' "$_cd_file" 2>/dev/null | grep -oE '[0-9]+' | head -1)"
if [ -n "${_name_n:-}" ] && [ "${_name_n:-}" = "${_body_n:-}" ]; then
  _ok "completions dispatch-table count" "$_body_n (name and assertion agree)"
else
  _stale "completions dispatch-table count" \
         "test name says ${_name_n:-<none>}, assertion says ${_body_n:-<none>}" \
         "update BOTH the assertion and the test name in $_cd_file"
fi

printf -- '----------------------------------------------------------\n'
if [ "$_fail" -eq 0 ]; then
  printf 'OK: %d derived-count surfaces all match the tree\n' "$_checks"
else
  printf 'STALE: at least one derived count is out of date (%d surfaces checked)\n' "$_checks"
fi
exit "$_fail"
