name: Test Installer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  bats-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          submodules: recursive
      - name: Run BATS tests
        run: tests/bats/bin/bats tests/install.bats

  bats-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          submodules: recursive
      - name: Run BATS tests (macOS)
        run: tests/bats/bin/bats tests/install.bats
